# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 048ab4edf6e04f3161ebb35d733d51e7145ef307b905f72330679e9a9f84c4a91ca5d23d5730fc69440ce3ca1b82c56289b0e85abf33bc71e2c00245f70273b5

test:
  secret_key_base: 62f103b74da0fbbfa9e41e9ec2760af3bf8f99ae524e25b8145cee09d41a02ae11655c85f2f960afeaba0559f0a4d2e8ba233f34e8dd2ee39381be653bb337c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
